### ISSUE TITLE
can't get dateset

### ISSUE THREAD

**Issue by huige555551** [joelthchao/tensorflow-finetune-flickr-style#12]
can you share you dateset in baidu cloud, it seem hard to get the dataset because of network time out!

**Comment by houguanqun** [comment]
I have the same trouble, could you share in google cloud? Thanks!

**Comment by joelthchao** [comment]
It depends on your network quality when connect to twitter image farm. I will try to upload one in google drive when I am available.

**Comment by joelthchao** [comment]
images: https://drive.google.com/open?id=1mR5jnSV-2Z3Okw3OB2z1rNwhruSKeY4y
urls: https://drive.google.com/open?id=1E5IgBHKRazk7KOZ4keZHAf3-FmuPWs3T
Put them under `tensorflow-finetune-flickr-style/`
