### ISSUE TITLE
How to download caffenet.npy?

### ISSUE THREAD

**Issue by yanmenglu** [joelthchao/tensorflow-finetune-flickr-style#2]
Hello,when I use this project and I have read the readme ,But I still don't konw how to download the caffenet.npy.please I tell me how to download that,or you can give me a Internet connection。Thank you very much!

**Comment by joelthchao** [comment]
1. Visit caffe model [page](https://github.com/BVLC/caffe/tree/master/models/bvlc_reference_caffenet) or directly download from [here](http://dl.caffe.berkeleyvision.org/bvlc_reference_caffenet.caffemodel)
2. Get the model definition [here](https://github.com/BVLC/caffe/blob/master/models/bvlc_reference_caffenet/train_val.prototxt)
3. Launch caffe-tensorflow's convertion:
```bash
git clone https://github.com/ethereon/caffe-tensorflow.git
cd caffe-tensorflow
python convert.py --caffemodel path/to/caffemodel --data-output-path path/to/output/caffenet.npy --code-output-path path/to/output/caffenet.py path/to/prototxt
```

**Comment by joelthchao** [comment]
Direct link: [here](https://drive.google.com/open?id=0B1TxGXQOCIQQME1peW9USXBDME0)
