### ISSUE TITLE
Is the code for finetuning?

### ISSUE THREAD

**Issue by micklexqg** [joelthchao/tensorflow-finetune-flickr-style#6]
Dear author, thanks for  your code, I am working on it. but I find that maybe it is not for finetuning as the model is not pretrained.
![image](https://user-images.githubusercontent.com/13776012/29460109-40842928-8459-11e7-941e-38c412426a0b.png)
![image](https://user-images.githubusercontent.com/13776012/29460120-4a135086-8459-11e7-8d0c-2ffb01371485.png)
how to load a pretrained model? would you like to paste the code?
another question, what're the .txt files look like? I want to make them with my own dataset as the some urls in .csv are invalid. 
thanks again, any help appreiated!

**Comment by joelthchao** [comment]
Load pre-trained model here: [code](https://github.com/joelthchao/tensorflow-finetune-flickr-style/blob/master/finetune.py#L52).

**Comment by micklexqg** [comment]
thanks
