### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by zzw1123** [joelthchao/tensorflow-finetune-flickr-style#8]
When I wanna download the flickr dataset,an error occurs:
 python assemble_data.py images train.txt test.txt 500
  File "assemble_data.py", line 67
    print('{} {}'.format(url, class_id), file=f)
                                             ^
SyntaxError: invalid syntax
Do you know what the reason is?

**Comment by zzw1123** [comment]
Oh it is because the version of my python is 2.7,and it maybe 3x of the authors.

**Comment by joelthchao** [comment]
Yes, we use Python 3
