### ISSUE TITLE
How do you know the style mapping?

### ISSUE THREAD

**Issue by wenmin-wu** [joelthchao/tensorflow-finetune-flickr-style#9]
Hi, thanks for your remarkable work! I want to download photos with more than 20 styles in your code. I search a lot on flickr website, but cannot find any document about the style mapping. Can you give me a link which talk about this? Thanks!

**Comment by joelthchao** [comment]
The style mapping is determined by the group name. For example, this [group](https://www.flickr.com/search/groups/?text=Depth%20of%20Field) collects images with "depth of field" style. You can search the style you are interested and find the group ids (in url).
